- name: Create app directory
  file:
    path: /home/ubuntu/app
    state: directory

- name: Copy calculator files
  copy:
    src: app/
    dest: /home/ubuntu/app/

- name: Build Docker image
  shell: docker build -t calculator-app /home/ubuntu/app

- name: Remove old container
  shell: docker rm -f calculator-app
  ignore_errors: yes

- name: Run new container
  shell: docker run -d --name calculator-app -p 8080:80 calculator-app